"""Access control for the DS scheduler gateway.

The gateway is deployed on each country machine and invoked once per request
(e.g. ``python3 scripts/ds_scheduler_entry.py --country cn --action ...``).
This module adds a light-weight enforcement layer on top of the existing
routing logic:

- loads a published access policy from ``config/access_policy.json``
  (generated by the duty platform);
- matches the caller by ``ds_token`` (tokens are bound to DS platform users
  by the duty platform);
- blocks disabled users, denied actions, delete actions outside the
  whitelist, and rate-limit violations ("large-scale" create/delete/etc.);
- keeps a rolling usage counter in ``config/access_state.json`` so limits
  survive across separate process invocations.

Enforcement can be disabled with the ``DS_ACCESS_DISABLE=1`` environment
variable (emergency bypass) or by setting ``enforce: false`` in the policy.

Only the Python standard library is used, matching the rest of the project.
"""

from __future__ import annotations

import json
import os
import tempfile
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

# ---------------------------------------------------------------------------
# Action classification (must stay in sync with src/ds-scheduler-access.mjs
# in the duty platform).
# ---------------------------------------------------------------------------

READ_ACTIONS = {
    "resolve_project",
    "list_alert_groups",
    "list_projects",
    "list_workflows",
    "get_workflow",
    "list_schedules",
    "get_schedule",
    "schedule_blast_radius",
    "list_instances",
    "get_instance",
    "list_task_instances",
    "get_task_log",
    "check_failed_instances",
    "list_datasources",
    "get_datasource",
    "extract_task_runtime_config",
    "list_resources",
    "view_resource_file",
    "search_resource_sql",
    "find_resource_usage",
    "search_country_git_sql",
    "dump_workflow_graph",
}

WRITE_ACTIONS = {
    "create_workflow",
    "create_schedule",
    "update_schedule",
    "batch_update_schedule_alerts",
    "append_task",
    "append_sql_task",
    "append_shell_task",
    "update_task",
    "update_sql_task",
    "update_shell_task",
}

CONTROL_ACTIONS = {
    "online_schedule",
    "offline_schedule",
    "online_workflow",
    "offline_workflow",
    "trigger_workflow",
    "retry_instance",
    "stop_instance",
    "force_fail_instance",
}

DELETE_ACTIONS = {
    "delete_task",
    "disable_tasks_except",
    "disable_task",
}

ACTION_CLASSES: Dict[str, str] = {}
for _action in READ_ACTIONS:
    ACTION_CLASSES[_action] = "read"
for _action in WRITE_ACTIONS:
    ACTION_CLASSES[_action] = "write"
for _action in CONTROL_ACTIONS:
    ACTION_CLASSES[_action] = "control"
for _action in DELETE_ACTIONS:
    ACTION_CLASSES[_action] = "delete"

ROLE_CLASSES: Dict[str, Set[str]] = {
    "readonly": {"read"},
    "operator": {"read", "write"},
    "power": {"read", "write", "control"},
    "admin": {"read", "write", "control", "delete"},
}

# Actions that count towards the "create" quota (large-scale new).
CREATE_METRIC_ACTIONS = {
    "create_workflow",
    "create_schedule",
    "append_task",
    "append_sql_task",
    "append_shell_task",
}
# Actions that count towards the "delete" quota (large-scale delete).
DELETE_METRIC_ACTIONS = DELETE_ACTIONS
# Actions that count towards the "trigger" quota.
TRIGGER_METRIC_ACTIONS = {
    "trigger_workflow",
    "retry_instance",
}

DEFAULT_LIMITS: Dict[str, int] = {
    "maxActionsPerHour": 200,
    "maxActionsPerDay": 500,
    "maxCreatesPerHour": 10,
    "maxCreatesPerDay": 30,
    "maxDeletesPerDay": 20,
    "maxTriggersPerHour": 30,
}


def classify_action(action: str) -> str:
    return ACTION_CLASSES.get(String_(action), "unknown")


def role_classes(role: str) -> Set[str]:
    return ROLE_CLASSES.get(String_(role), {"read"})


def String_(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


def as_bool(value: Any, fallback: bool = False) -> bool:
    """Coerce JSON booleans robustly (handles ``"false"`` / 0 / 1 too)."""
    if isinstance(value, bool):
        return value
    if value is None:
        return fallback
    if isinstance(value, (int, float)):
        return value != 0
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


# 窗口时区偏移（秒）。默认 UTC+8（北京时间），与值班平台审计时间/预览保持一致，
# 可用环境变量 DS_ACCESS_TZ_OFFSET 覆盖（例如墨西哥 -6 小时填 -21600）。
TZ_OFFSET_SECONDS = int(os.environ.get("DS_ACCESS_TZ_OFFSET", "28800"))


def normalize_policy(raw: Any) -> Dict[str, Any]:
    """Sanitize a parsed policy JSON object into the shape the gateway uses."""
    if not isinstance(raw, dict):
        return {}
    tokens_raw = raw.get("tokens")
    tokens: Dict[str, Any] = {}
    if isinstance(tokens_raw, dict):
        for token, entry in tokens_raw.items():
            if not token:
                continue
            if not isinstance(entry, dict):
                continue
            role = String_(entry.get("role"))
            if role not in ROLE_CLASSES:
                role = "operator"
            allowed = entry.get("allowedActions")
            denied = entry.get("deniedActions")
            tokens[token] = {
                "user": String_(entry.get("user")),
                "role": role,
                "enabled": as_bool(entry.get("enabled"), True),
                "allowedActions": list(allowed) if isinstance(allowed, list) else None,
                "deniedActions": set(str(a) for a in (denied or []) if a),
                "deleteAllowed": as_bool(entry.get("deleteAllowed"), False),
                "limits": entry.get("limits") if isinstance(entry.get("limits"), dict) else {},
            }
    limits_raw = raw.get("globalLimits")
    limits: Dict[str, int] = {}
    if isinstance(limits_raw, dict):
        for key in DEFAULT_LIMITS:
            value = limits_raw.get(key)
            if isinstance(value, (int, float)) and not isinstance(value, bool):
                limits[key] = max(0, int(value))
    default_role = String_(raw.get("defaultRole"))
    if default_role not in ROLE_CLASSES:
        default_role = "operator"
    return {
        "version": raw.get("version"),
        "enforce": bool(raw.get("enforce", True)),
        "generatedAt": String_(raw.get("generatedAt")),
        "defaultRole": default_role,
        "enforceUnknown": bool(raw.get("enforceUnknown", True)),
        "globalLimits": limits,
        "tokens": tokens,
    }


def _default_policy() -> Dict[str, Any]:
    return {
        "version": 1,
        "enforce": False,
        "generatedAt": "",
        "defaultRole": "operator",
        "enforceUnknown": True,
        "globalLimits": dict(DEFAULT_LIMITS),
        "tokens": {},
    }


def effective_limits(entry: Optional[Dict[str, Any]], policy: Dict[str, Any]) -> Dict[str, int]:
    """Merge global limits with a per-token override (entry)."""
    limits = dict(DEFAULT_LIMITS)
    limits.update(policy.get("globalLimits") or {})
    if entry and isinstance(entry.get("limits"), dict):
        for key, value in entry["limits"].items():
            if key in limits and isinstance(value, (int, float)) and not isinstance(value, bool):
                limits[key] = max(0, int(value))
    return limits


class AccessController:
    """Enforce the published access policy for a single request."""

    def __init__(
        self,
        policy_path: Optional[str] = None,
        state_path: Optional[str] = None,
        now: Optional[float] = None,
        disabled: Optional[bool] = None,
    ) -> None:
        project_root = Path(__file__).resolve().parent.parent
        self.policy_path = Path(
            policy_path or os.environ.get("DS_ACCESS_POLICY") or project_root / "config" / "access_policy.json"
        )
        self.state_path = Path(
            state_path or os.environ.get("DS_ACCESS_STATE") or project_root / "config" / "access_state.json"
        )
        self.disabled = (
            disabled if disabled is not None else String_(os.environ.get("DS_ACCESS_DISABLE")) == "1"
        )
        self._now = now if now is not None else time.time()
        self.policy = self._load_policy()

    # -- policy loading ------------------------------------------------------

    def _load_policy(self) -> Dict[str, Any]:
        try:
            raw = json.loads(self.policy_path.read_text(encoding="utf-8"))
            return normalize_policy(raw)
        except FileNotFoundError:
            return _default_policy()
        except Exception as exc:  # pragma: no cover - defensive
            print(f"[access] failed to load policy {self.policy_path}: {exc}", file=os.sys.stderr)
            return _default_policy()

    # -- time windows --------------------------------------------------------

    @staticmethod
    def _hour_key(ts: float) -> str:
        return "h_" + time.strftime("%Y-%m-%dT%H", time.gmtime(ts + TZ_OFFSET_SECONDS))

    @staticmethod
    def _day_key(ts: float) -> str:
        return "d_" + time.strftime("%Y-%m-%d", time.gmtime(ts + TZ_OFFSET_SECONDS))

    def _buckets(self) -> Dict[str, Dict[str, Dict[str, int]]]:
        """Load usage state and keep only the current rolling windows."""
        try:
            raw = json.loads(self.state_path.read_text(encoding="utf-8"))
            buckets = raw.get("buckets") if isinstance(raw, dict) else None
        except FileNotFoundError:
            buckets = None
        except Exception:
            buckets = None
        if not isinstance(buckets, dict):
            return {}
        hour_key = self._hour_key(self._now)
        day_key = self._day_key(self._now)
        pruned: Dict[str, Dict[str, Dict[str, int]]] = {}
        for token, per_token in buckets.items():
            if not isinstance(per_token, dict):
                continue
            keep = {}
            if hour_key in per_token and isinstance(per_token[hour_key], dict):
                keep[hour_key] = per_token[hour_key]
            if day_key in per_token and isinstance(per_token[day_key], dict):
                keep[day_key] = per_token[day_key]
            if keep:
                pruned[token] = keep
        return pruned

    def _persist_buckets(self, buckets: Dict[str, Dict[str, Dict[str, int]]]) -> None:
        self.state_path.parent.mkdir(parents=True, exist_ok=True)
        payload = {"updatedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(self._now)), "buckets": buckets}
        # Atomic write to avoid corrupting the state file on concurrent requests.
        fd, tmp = tempfile.mkstemp(dir=str(self.state_path.parent), suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                json.dump(payload, fh, ensure_ascii=False)
            os.replace(tmp, str(self.state_path))
        finally:
            try:
                os.unlink(tmp)
            except OSError:
                pass

    # -- metric accounting ---------------------------------------------------

    def _metric_for_action(self, action: str) -> List[str]:
        metrics = []
        if action in CREATE_METRIC_ACTIONS:
            metrics.append("creates")
        if action in DELETE_METRIC_ACTIONS:
            metrics.append("deletes")
        if action in TRIGGER_METRIC_ACTIONS:
            metrics.append("triggers")
        return metrics

    def _record_usage(self, token: str, action: str, buckets: Dict[str, Dict[str, Dict[str, int]]]) -> None:
        per_token = buckets.setdefault(token, {})
        hour_key = self._hour_key(self._now)
        day_key = self._day_key(self._now)
        hour_bucket = per_token.setdefault(hour_key, {"total": 0, "creates": 0, "deletes": 0, "triggers": 0})
        day_bucket = per_token.setdefault(day_key, {"total": 0, "creates": 0, "deletes": 0, "triggers": 0})
        hour_bucket["total"] = int(hour_bucket.get("total", 0)) + 1
        day_bucket["total"] = int(day_bucket.get("total", 0)) + 1
        for metric in self._metric_for_action(action):
            hour_bucket[metric] = int(hour_bucket.get(metric, 0)) + 1
            day_bucket[metric] = int(day_bucket.get(metric, 0)) + 1

    def _with_state_lock(self, fn):
        """Serialize the read-check-write cycle against concurrent requests.

        Uses fcntl.flock on a lock file next to the state file. On platforms
        without fcntl (e.g. Windows) it degrades to best-effort without a lock.
        """
        self.state_path.parent.mkdir(parents=True, exist_ok=True)
        lock_path = str(self.state_path) + ".lock"
        fd = os.open(lock_path, os.O_CREAT | os.O_RDWR, 0o644)
        locked = False
        try:
            try:
                import fcntl
                fcntl.flock(fd, fcntl.LOCK_EX)
                locked = True
            except (ImportError, OSError):
                pass
            return fn()
        finally:
            if locked:
                try:
                    import fcntl
                    fcntl.flock(fd, fcntl.LOCK_UN)
                except (ImportError, OSError):
                    pass
            os.close(fd)

    def _check_limits_and_record(self, token, action, user, action_class, entry):
        """Limit check + usage record, executed atomically under a state lock."""
        limits = effective_limits(entry, self.policy)
        buckets = self._buckets()
        hour_key = self._hour_key(self._now)
        day_key = self._day_key(self._now)
        usage = buckets.get(token) or {}
        hour_usage = usage.get(hour_key) or {}
        day_usage = usage.get(day_key) or {}
        total_hour = int(hour_usage.get("total", 0))
        total_day = int(day_usage.get("total", 0))
        creates_hour = int(hour_usage.get("creates", 0))
        creates_day = int(day_usage.get("creates", 0))
        deletes_day = int(day_usage.get("deletes", 0))
        triggers_hour = int(hour_usage.get("triggers", 0))
        # A specific limit only applies to actions that count towards that
        # metric (e.g. create-quota does not block reads).
        metrics = set(self._metric_for_action(action))
        checks = [
            ("maxActionsPerHour", total_hour, "小时总操作数", True),
            ("maxActionsPerDay", total_day, "当日总操作数", True),
            ("maxCreatesPerHour", creates_hour, "小时新建数", "creates" in metrics),
            ("maxCreatesPerDay", creates_day, "当日新建数", "creates" in metrics),
            ("maxDeletesPerDay", deletes_day, "当日删除/禁用数", "deletes" in metrics),
            ("maxTriggersPerHour", triggers_hour, "小时触发数", "triggers" in metrics),
        ]
        for key, actual, label, applies in checks:
            if not applies:
                continue
            limit = limits.get(key)
            if limit is not None and actual >= limit:
                return {
                    "allowed": False,
                    "code": "ACCESS_LIMIT_EXCEEDED",
                    "message": f"用户 {user or token} 触发管控阈值：{label} {actual} 已达上限 {limit}（策略 {key}）",
                    "detail": {
                        "token": token,
                        "user": user,
                        "action": action,
                        "actionClass": action_class,
                        "limitKey": key,
                        "limit": limit,
                        "actual": actual,
                    },
                }
        self._record_usage(token, action, buckets)
        self._persist_buckets(buckets)
        return {"allowed": True, "code": None, "message": "", "detail": None}

    # -- decision ------------------------------------------------------------

    def authorize(self, token: str, action: str) -> Dict[str, Any]:
        """Return a decision dict for one request.

        Keys: ``allowed``, ``code``, ``message``, ``detail`` (dict with
        ``token``, ``user``, ``action``, ``actionClass``, ``limits`` when a
        limit was hit).
        """
        token = String_(token)
        action = String_(action)
        decision: Dict[str, Any] = {"allowed": True, "code": None, "message": "", "detail": None}
        if self.disabled or not self.policy.get("enforce"):
            return decision

        entry = self.policy.get("tokens", {}).get(token)
        user = (entry or {}).get("user", "")

        # Static permission check.
        if entry is not None and not entry["enabled"]:
            return {
                "allowed": False,
                "code": "ACCESS_USER_DISABLED",
                "message": f"用户 {user or token} 已被禁用，禁止通过 DS 网关执行操作",
                "detail": {"token": token, "user": user, "action": action, "actionClass": classify_action(action)},
            }

        action_class = classify_action(action)
        if entry is not None:
            denied = entry["deniedActions"]
            allowed_list = entry["allowedActions"]
            classes = role_classes(entry["role"])
            delete_allowed = entry["deleteAllowed"]
        else:
            # Unknown token: enforced read-only by default.
            denied = set()
            allowed_list = None
            classes = {"read"} if self.policy.get("enforceUnknown", True) else role_classes(self.policy.get("defaultRole", "operator"))
            delete_allowed = False

        if action in denied:
            return self._deny("ACCESS_ACTION_DENIED", f"用户 {user or token} 无权执行动作 {action}", token, user, action, action_class)
        if allowed_list is not None and action not in set(allowed_list):
            return self._deny("ACCESS_ACTION_NOT_ALLOWED", f"用户 {user or token} 不在 {action} 的动作白名单内", token, user, action, action_class)
        if action_class not in classes and not (action_class == "delete" and delete_allowed):
            reason = "用户未开放删除权限" if action_class == "delete" else f"用户角色不允许 {action_class} 类操作"
            return self._deny("ACCESS_CLASS_DENIED", f"用户 {user or token} {reason}（{action}）", token, user, action, action_class)

        # Rate / volume limits (under lock to avoid burst bypass).
        return self._with_state_lock(lambda: self._check_limits_and_record(token, action, user, action_class, entry))

    @staticmethod
    def _deny(code, message, token, user, action, action_class) -> Dict[str, Any]:
        return {
            "allowed": False,
            "code": code,
            "message": message,
            "detail": {"token": token, "user": user, "action": action, "actionClass": action_class},
        }
